'use client'

import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

import { metadata } from './metadata'
import { usePathname } from 'next/navigation'
import { useEffect, useState } from 'react'
import { rootFetch } from '@/utils/fetch'
import useBookStore from '@/store/bookStore'
import useCategoryStore from '@/store/categorieStore'

const inter = Inter({ subsets: ['latin'] })

metadata.title = 'Create Next App'
metadata.description = 'Generated by create next app'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()

  const adminurl = pathname.includes('/admin')

  const [isDataLoaded, setIsDataLoaded] = useState(false)

  useEffect(() => {
    const fetchData = async () => {
      try {
        await rootFetch({
          setBooks: useBookStore.getState().setBooks,
          setCategories: useCategoryStore.getState().setCategories,
        })

        setIsDataLoaded(true)
      } catch (error) {
        console.error('Error during data fetching:', error)
        setIsDataLoaded(true)
      }
    }

    fetchData()

    const intervalId = setInterval(fetchData, 5 * 60 * 1000)

    return () => clearInterval(intervalId)
  }, [])

  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='flex flex-col items-center w-screen h-min-screen bg-gradient-to-r from-green-200 to-green-500'>
          {adminurl ? null : <Header />}

          {children}
        </main>
      </body>
    </html>
  )
}
