'use client'

import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

import { metadata } from './metadata'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

metadata.title = 'Create Next App'
metadata.description = 'Generated by create next app'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()

  const adminurl = pathname.includes('/admin')

  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='flex flex-col items-center w-screen h-screen bg-gradient-to-r from-green-200 to-green-500'>
          {adminurl ? null : <Header />}

          {children}
        </main>
      </body>
    </html>
  )
}
