'use client'

import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import useUserStore from '@/store'
import { metadata } from './metadata'

const inter = Inter({ subsets: ['latin'] })

metadata.title = 'Create Next App'
metadata.description = 'Generated by create next app'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { user } = useUserStore()
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='flex flex-col items-center w-screen h-screen bg-slate-400'>
          {user && user.role === 'admin' ? null : <Header />}

          {children}
        </main>
      </body>
    </html>
  )
}
