version: '3'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    restart: always
    depends_on:
      - server

  server:
    container_name: server
    image: server
    build:
      context: ./server
      dockerfile: server.dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@bookshop:5432/postgres?schema=public
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD
      POSTGRES_DB: bookshop
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  pgdata: {}
                 