import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { Toaster } from 'sonner';
import { UserProvider } from '@/contexts/userContext';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Fake News Portal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang='en'>
      <body className={inter.className}>
        <UserProvider>
          <Toaster position='top-center' richColors />

          {children}
        </UserProvider>
      </body>
    </html>
  );
}
