import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/home/Header'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
 

  return (
    <html lang='en'>
      <body className={inter.className}>
      <main className='flex flex-col items-center w-screen h-min-screen bg-gradient-to-r from-green-200 to-green-500'>
          <Header />

          {children}
        </main>
      </body>
    </html>
  )
}
